"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - to_lf1
          - to_lf2
          - to_lf3
          - to_rf1
          - to_rf2
          - to_rf3
          - to_lh1
          - to_lh2
          - to_lh3
          - to_rh1
          - to_rh2
          - to_rh3

      gains:
        to_lf1 : {p: 15, d: 0.005, i: 2.5}
        to_lf2 : {p: 15, d: 0.005, i: 2.5}
        to_lf3 : {p: 15, d: 0.005, i: 2.5}
        to_rf1 : {p: 15, d: 0.005, i: 2.5}
        to_rf2 : {p: 15, d: 0.005, i: 2.5}
        to_rf3 : {p: 15, d: 0.005, i: 2.5}
        to_lh1 : {p: 15, d: 0.005, i: 2.5}
        to_lh2 : {p: 15, d: 0.005, i: 2.5}
        to_lh3 : {p: 15, d: 0.005, i: 2.5}
        to_rh1 : {p: 15, d: 0.005, i: 2.5}
        to_rh2 : {p: 15, d: 0.005, i: 2.5}
        to_rh3 : {p: 15, d: 0.005, i: 2.5}
