left_front:
  - to_lf1
  - to_lf2
  - to_lf3
  - to_lffoot

right_front:
  - to_rf1
  - to_rf2
  - to_rf3
  - to_rffoot

left_hind:
  - to_lh1
  - to_lh2
  - to_lh3
  - to_lhfoot

right_hind:
  - to_rh1
  - to_rh2
  - to_rh3
  - to_rhfoot